### ISSUE TITLE
INC298716201 - 1v1 matching based on least-played

### ISSUE THREAD

**Issue by tksalathe** [bi3mer/1v1#1]
It appears the "Matches of the Hour" are randomized without taking into account who each person has already played. 

This can result in multiple duplicate matches of the hour where two players may play eachother more than once in consecutive matches. 

IMPACT: This may necessarily skew results as a player of high skill (eg. Jahbasedgod) can be matched multiple times against a player of low skill (eg. itsdoodoobaby), resulting in skewed leaderboards. 

PROPOSED FIX: Implement matching based on who each opponent has played the least.

**Comment by tksalathe** [comment]
Great idea, tksalathe!

Sounds like low-hanging fruit we can capitalize on to better improve the 1v1 matching.

**Comment by bi3mer** [comment]
Implemented
